### ISSUE TITLE
MultipartFormDataParser does not accept quoted boundary value

### ISSUE THREAD

**Issue by Halofreak1990** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#53] opened 2017-02-16 21:24 UTC
The current version of the MultipartFormDataParser does not work when the boundary value specified in the header is enclosed in quotes, such as when produced by the `System.Net.Http.MultipartFormDataContent` class.

A workaround can be found in the answer to [this](http://stackoverflow.com/questions/21569770/wrong-content-type-header-generated-using-multipartformdatacontent) stackoverflow question regarding the aforementioned .NET class, but, according to the RFC linked in the comment (https://tools.ietf.org/html/rfc2046#section-5.1.1), a quoted boundary is used when the boundary value may include 'invalid' characters, and as such should be accepted by the MultipartFormDataParser.

**Comment by Jericho** [comment] 2020-03-31 17:08
@Halofreak1990 I know you reported this issue quite some time ago (3 years!) but I recently took over stewardship of this project and I'm trying to address outstanding issues. I would like to take a look at the problem you reported and figure out a solution.

I used the C# code in the StackOverflow question you linked and I do notice the quoted boundary in the header but since our parser does not rely on this header value to determine the boundary, I haven't been able to reproduce any problem. Our parser reads the first line of the payload to determine the boundary and since this this value is not quoted, I don't observe any problem.

Maybe the parser relied on the header value at the time you reported this issue? If I'm missing something or misunderstood the problem, feel free to correct me.

Again, I realize you reported this issue quite a long time ago and you have probably moved on but  I would really appreciate if you could let me know if you feel this is still an issue that should be investigated.

**Comment by Jericho** [comment] 2020-04-29 14:12
I'm going to close this issue but feel free to comment with additional information.

**Closed by Jericho** 2020-04-29 14:12 UTC
Labels: question
